import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        outline: "#8b90a0",
        "error-container": "#93000a",
        "on-tertiary-container": "#4c1a00",
        "primary-container": "rgb(var(--primary-container) / <alpha-value>)",
        "surface-variant": "#353535",
        "on-secondary-fixed": "#1a1c1c",
        "on-surface": "rgb(var(--on-surface) / <alpha-value>)",
        "inverse-primary": "#005bc1",
        "border-subtle": "var(--border-subtle)",
        "on-primary-fixed-variant": "#004493",
        "tertiary-container": "#ef6719",
        "text-muted": "rgb(var(--text-muted) / <alpha-value>)",
        "tertiary-fixed": "#ffdbcc",
        "inverse-on-surface": "#303030",
        "on-tertiary-fixed": "#351000",
        "on-error": "#690005",
        error: "#ffb4ab",
        "surface-tint": "#adc6ff",
        "glow-blue": "rgba(0, 122, 255, 0.3)",
        "tertiary-fixed-dim": "#ffb595",
        surface: "rgb(var(--surface) / <alpha-value>)",
        secondary: "#c6c6c7",
        "surface-container-lowest":
          "rgb(var(--surface-container-lowest) / <alpha-value>)",
        "on-error-container": "#ffdad6",
        "primary-fixed-dim": "#adc6ff",
        "surface-container-highest":
          "rgb(var(--surface-container-highest) / <alpha-value>)",
        "secondary-fixed-dim": "#c6c6c7",
        background: "rgb(var(--background) / <alpha-value>)",
        "on-tertiary-fixed-variant": "#7c2e00",
        "surface-container-high":
          "rgb(var(--surface-container-high) / <alpha-value>)",
        "on-primary-container":
          "rgb(var(--on-primary-container) / <alpha-value>)",
        "on-primary": "rgb(var(--on-primary) / <alpha-value>)",
        primary: "rgb(var(--primary) / <alpha-value>)",
        "on-background": "rgb(var(--on-background) / <alpha-value>)",
        "on-secondary-fixed-variant": "#454747",
        "secondary-container": "#454747",
        "on-primary-fixed": "#001a41",
        "inverse-surface": "#e2e2e2",
        "primary-fixed": "#d8e2ff",
        "surface-container-low":
          "rgb(var(--surface-container-low) / <alpha-value>)",
        tertiary: "#ffb595",
        "surface-dim": "rgb(var(--surface-dim) / <alpha-value>)",
        "secondary-fixed": "#e2e2e2",
        "on-tertiary": "#571e00",
        "on-secondary-container": "#b4b5b5",
        "on-secondary": "#2f3131",
        "surface-container": "rgb(var(--surface-container) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--on-surface-variant) / <alpha-value>)",
        "outline-variant": "#414755",
        "surface-glass": "rgba(255, 255, 255, 0.88)",
        "surface-bright": "#393939",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        "section-gap": "120px",
        gutter: "24px",
        "section-gap-mobile": "64px",
        "container-max": "1200px",
        "margin-mobile": "20px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "system-ui", "sans-serif"],
        "headline-lg": ["var(--font-inter)"],
        "headline-md": ["var(--font-inter)"],
        "body-lg": ["var(--font-inter)"],
        "body-md": ["var(--font-inter)"],
        "display-hero": ["var(--font-inter)"],
        "display-hero-mobile": ["var(--font-inter)"],
        "label-caps": ["var(--font-inter)"],
        "mono-label": ["var(--font-jetbrains)", "monospace"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-hero": [
          "72px",
          { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" },
        ],
        "display-hero-mobile": [
          "40px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "mono-label": ["13px", { lineHeight: "1.0", fontWeight: "500" }],
        "label-caps": [
          "12px",
          { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
